### ISSUE TITLE
Unicode Encoding will cause error in assemble_header.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#10]
When a response header contains the `Content-Disposion` field, it may contains some none ascii character, and as a result causing the assemble_header failed. 
We need to deal with this kind of condition.

**Comment by mike820324** [comment]
The root cause of this issue is that http-parser will return `unicdoe` string for all header field and as a result, when formating a string into byte string it will cause the problem.
Currently, we can just add `enocde("utf8")` after every header field to solved this issue.

**Comment by chhsiao90** [comment]
Is it work if we add the b before the string like this:

```
http_header_query_str = b"{0} {1} HTTP/{2}".format(self.method, self.url, self.version)
http_header_fields = [ b"{0}: {1}".format(key, self.header[key]) for key in self.header ]
http_header_list = [http_header_query_str]
http_header_list.extend(http_header_fields)
return b"{0}\r\n\r\n".format("\r\n".join(http_header_list))
```

**Comment by mike820324** [comment]
Unfortunately, it will still raise the same exception. 
The problem is that `self.header[key]` is a **unicode string**, and the format method will encode the **unicode string** into the string type. 

> Note that, in python 2 the byte string is basically the same as a normal string. But in python3, the default string type is unicode.

The root cause for this issue is that http-parser will help us encode the headers into unicode. And we have no idea what is the original encoding method, that is the root cause.

I may need to dig further into http-parser, or survey more about the pycohttpparser since pycohttpparser will return the byte string to us and is more suitable for our need.

**Comment by chhsiao90** [comment]
Got it!

BTW,
I had seen http-parser source code.
It just so str(data) in python 2.7

I m not sure that this will help or not, haha

**Comment by mike820324** [comment]
Commit ec8f151 fix this issue.
