### ISSUE TITLE
Socks remote dns support.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#11]
It is a nice to have feature especially when logging the info.
Currently, the info that we log out only contains the src/dest ip. 
If we can have the remote dns support, it is possible to log the info with the host name, instead of ip address.

**Comment by mike820324** [comment]
Currently we use `read_bytes` to get the socks request data; however, the remote dns will send the host name as the request data and the length of the host name is unknown.
The approach that I'm going to use maybe,
1. get socks request headers, `read_bytes(4)`
2. may be three different conditions
   - ipv4: read 6 more bytes  `read_bytes(6)`
   - ipv6: read 18 more bytes `read_bytes(18)`
   - host name: read 1 byte to determine host name size, and read n+2 bytes.

**Comment by chhsiao90** [comment]
Just a reminder:

First, read_bytes(4) for the first 4 bytes.
And the 4th byte determine the address type
- 4 bytes for IPv4 address
- 1 byte of name length followed by the name for domain name
- 16 bytes for IPv6 address

And we will go next read_bytes depend on the 4th byte

**Comment by mike820324** [comment]
Thanks for the reminder, I will try the new approach when I got some time.

**Comment by mike820324** [comment]
Commit 960d79f fix this issue.
