### ISSUE TITLE
[Proposal]: Support Replay Request

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#110]
Should be able to support replay request.
- [x] TUI Viewer support.
  - [x] User can choose which session to dump.
- [x] Support the following two format.
  - [x] json
  - [x] mitmproxy compatible
- [x] Replayer utility
  - [x] http 1.1
  - [x] http 2.0
- [x] console replay
  - [x] export replay script
  - [x] run replay script
- [x] tui replay
  - [x] export replay script
  - [x] run replay script

**Comment by mike820324** [comment]
As discussed today, I think using another process to replay request may be a better solution. (Keep the proxy itself clean. )

Some todos are listed below:
- A viewer to dump request. 
- Using [request](http://docs.python-requests.org/en/master/) module or curl to replay the request body. (call replay.py or something.)

The `replay.py` should also have a subcommand(replay and command line options.)
- proxy-host: server address
- proxy-port: server port
- file: input filename
- format: input file format(json | mitmproxy)

ex.

``` bash
microproxy replay --proxy-host 127.0.0.1 --proxy-port 5580 --file test --format json
```

As for the file format.
- json (direct dump to file)
- mitmproxy compatible format.

**Comment by mike820324** [comment]
I'll start to work on the viewer dumper when I'm free today. ;D

**Comment by chhsiao90** [comment]
For viewer dumped, I need work on gviewer v2.1.0 for the functionality to bind user defined actions.
I would start work on it ASAP.

**Comment by mike820324** [comment]
wow, thank. In the meanwhile, I'll work on a basic dumper which is  just some modification of the old `console.py`.

**Comment by chhsiao90** [comment]
Haha, I'm so happy that console mode hadn't been forgot.

**Comment by chhsiao90** [comment]
I had implement action binding on gviewer.
Please reference the commit https://github.com/chhsiao90/gviewer/commit/e1e778862e68fc260bfe7966fbb29fec77780405
I will release it as v2.1.0 soon.

So I think I will start work on the feature: export replay script by viewer

**Comment by mike820324** [comment]
Great to hear that. I'm resolving some other issue using the socks5 library. I'll push a new branch so that you may test this as well.

**Comment by chhsiao90** [comment]
I separate a issue #123 for record the tui part progress

**Comment by chhsiao90** [comment]
Reference #136

**Comment by mike820324** [comment]
Add mitmproxy compatiable layer next time.
Currently json format is good enough.

**Comment by mike820324** [comment]
This issue can be closed, all related issues are done.
