### ISSUE TITLE
[Readme] Suggest: Change "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by hynguyen2610** [mike820324/microProxy#111]
In readme.md

> Project Installation
> 
> Since we do not have setup.py yet, you can not use setuptool to install this project. Currently, you have to clone the project and use pip to install the requirements.
> 
> git clone https://github.com/mike820324/microProxy.git
> cd microProxy
> pip install -r requirements.txt

The cloned microProxy folder don't have requirements.txt. Instead, it have requirements folder, with 3 txt files. I suggest change it to `pip install -r requirements/*.txt`

**Comment by mike820324** [comment]
Thank you reporting this issue. Currently the README is a little bit out of date.

I'm currently working on a new README, which can be found in this link,
https://github.com/mike820324/microProxy/blob/Readme-Enhancement-%2376/README.md

If you still found any issues based on the new README, feel free to leave a comment or send a PR.
Thanks.
