### ISSUE TITLE
[Proposal]: Adding websocket

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#115]
Websocket support.

Currently, microproxy can not properly deal with website that use websocket.

**Comment by mike820324** [comment]
https://tools.ietf.org/html/rfc6455

**Comment by chhsiao90** [comment]
It sesms that mitmproxy not support for websocket.
It only record for the upgrade request, but the websocket connections seems not connect to each other successfully.
I had test https://www.websocket.org/echo.html with mitiproxy v0.17.1

**Comment by mike820324** [comment]
I have also tested the master branch, I can also confirmed this behavior.
