### ISSUE TITLE
[Proposal]: Export microproxy server logger to viewer

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#116]
I would like to propose  a new feature that will add a new zmq channel to viewer so that the viewer can receive the loggin information from the proxy server.

**Comment by chhsiao90** [comment]
loggin info? like socks proxy username/password?

I think it's good idea for viewer to collect different information from proxy!

**Comment by mike820324** [comment]
The title may be misleading. 
What I mean is the microproxy server logger information. (ex. logging data in different layer.) something like that.

**Comment by chhsiao90** [comment]
Got it. Good feature.
So we should not just simply used logger.
Maybe we should wrap it in LogManager?

**Comment by mike820324** [comment]
Yeah, something like that or maybe better.
It seems like zmq has this feature already.

http://pyzmq.readthedocs.io/en/latest/logging.html
Maybe we can utilize this part.
