### ISSUE TITLE
[Proposal]: Create event queue on proxy server for replay

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#118]
I think it may be a good practice to create a queue for handling event between process and process.
So I think we should create a queue on server, so that client/viewer could do replay by put replay request on it.
Of cause, the queue could provide other function if need!

**Comment by mike820324** [comment]
Good idea. 
Does this mean the proxy server should add a zmq request/response pattern??

**Comment by mike820324** [comment]
Or there are some other pattern that we can use. I'm not quite sure though. ;)

**Comment by mike820324** [comment]
Reference #110

**Comment by chhsiao90** [comment]
Request/Response is enough!

**Comment by mike820324** [comment]
Okay then, let's change the pattern to request and response. This will also open a door for many other different possibilities. (client/viewer can control the some of the behavior of proxy server)
I really forward to see this happening.
:)

**Comment by chhsiao90** [comment]
Did change mean remove pub/sub?
My idea is keep pin/din, but also create another req/resp pattern.
But I need find out is there anyway to extend the req/resp with using the same socket/port.

**Comment by mike820324** [comment]
I think keeping pub/sub may be a better approach.
Do we need to stick to the same port, (If zmq native support same socket/port, go ahead) or just adding another channel?

**Comment by chhsiao90** [comment]
It seems that zmq is hard to support req/rep, pin/sub at same port (or not support)
So maybe create another socket is the solution!

**Comment by mike820324** [comment]
ok, then adding a new command line option to specify the channel address and port.

**Comment by chhsiao90** [comment]
Sorry, I reference a wrong issue no... XD

**Comment by mike820324** [comment]
Based on the current code implementation, I'm curious that is it possible to change the `ReplayHandler` into a kind of layer, and use LayerManager to handle the rest.

```
class EventManager(object):
...
def _on_recv(self, msg_parts):
   ...
   else:
      # creating pipe in this stage or any other better place.
      layer_manager = LayerManager()
      layer_manager.run_layers(self, read_stream)


# within LayerManager
def get_first_layer(self, context):
   if isinstance(context.src_stream, PipedStream):
      return ReplayLayer()
   else:
      # old code

```

The draw back of this kind of approach is when and where do we put the `_make_http1_request`, maybe dispatch to a queue or something.

**Comment by chhsiao90** [comment]
It's ok to turn it into layer and run it by LayerManager.
Thx for the advice!

**Comment by mike820324** [comment]
Further implementation discussion will move to PR #132

**Comment by mike820324** [comment]
PR #132 solved this issue.
