### ISSUE TITLE
[Http1Layer]: Using h11 as protocol implementation

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#119]
Currently the only protocol implementation that we depend on tornado is http1 layer. I think it should be okay to use h11 as our protocol implementation. 

The benefit of this approach is that, the only dependency of tornado is the ioloop implementation. If one day we want to use another io loop implementation, there will be less painful.

**Comment by mike820324** [comment]
By the way, I'll push my own prototype version to a new branch tonight.

**Comment by chhsiao90** [comment]
Yeah! I will wait for your prototype and work on it.

**Comment by mike820324** [comment]
When testing with the h11-refactor branch, please install the github master version of h11 since there are some api changes.

**Comment by mike820324** [comment]
As previously discussed, we may need to add a sub module for h11 until the h11 release the latest version to pypi.

**Comment by chhsiao90** [comment]
Resolved by #127
