### ISSUE TITLE
[Viewer]: Move decode body with base64 from viewer to formatter

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#124]
More clean, and will help implement #123 export replay script

**Comment by chhsiao90** [comment]
May wait for #121 merged

**Comment by mike820324** [comment]
Can you describe more about this issue.
Some code snippets will be helpful.
:)

**Comment by chhsiao90** [comment]
Sure!
Currently, the viewer try format body, will need decode base64 before call Formatter's format function.
I think let the formatter do the decode is better than viewer decode itself.

For #123 part, because the viewer will decode body when received message,
and it will cause problem when we export replay script that json will contains body with original content (may in Binary format).
Here we could do encode before export, but I think that's not cool.
So I suggest move decode into formatter.

Current tui
https://github.com/mike820324/microProxy/blob/master/microproxy/viewer/tui.py#L92-L99

``` python
class ZmqAsyncDataStore(gviewer.AsyncDataStore):
    def transform(self, message):
        message_dict = json.loads(message[0])
        message_dict["request"]["body"] = \
            message_dict["request"]["body"].decode("base64")
        message_dict["response"][
"body"] = \
            message_dict["response"]["body"].decode("base64")
        return message_dict
```

Current console
https://github.com/mike820324/microProxy/blob/console-enhance-%23121/microproxy/viewer/console.py#L132-L146

``` python
class Response(TextList):
    HEADER_TITLE = "Response Headers:"
    BODY_TITLE = "Response Body:"
    FG_COLOR = "blue"
    ATTRS = ["bold"]

    def __init__(self, response, show_body=False):
        content = []
        content.append(ColorText(self.HEADER_TITLE, fg_color=self.FG_COLOR, attrs=self.ATTRS))
        content.append(Header(response["headers"]))
        if show_body and response["body"]:
            response["body"] = response["body"].decode("base64")
            content.append(ColorText(self.BODY_TITLE, fg_color=self.FG_COLOR, attrs=self.ATTRS))
            content = content + _formatter.format_request(response)
        super(Response, self).__init__(content)
```

**Comment by mike820324** [comment]
Sounds good to me.
Do you want to just use the same PR(https://github.com/mike820324/microProxy/pull/122) to resolve this part??
