### ISSUE TITLE
Use Publish/Subscribe Patten over zmq

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#13]
Because the action to write to or read from zmq didn't change the behavior to response the original response to the sender(browser),
it only used to recording.
So I suggest use the listener pattern with zmq publish/subscribe implementation.

**Comment by mike820324** [comment]
This is a very good question and it also brings up another issue, 

> **do we need to change the request header/response data.**

If we decide to use a listener(pub/sub) pattern, I believe it might not be possible to modify the request/response data. ( I'm not that familiar with mq, so correct me if I'm wrong ;) )

As a result, I believe it is a good place to discuss what is the purpose of this project and what kind of features we would like to add to this project in the future.

Personally,  I would like to added the following features to this project:
- HTTP / HTTP2 / WebSocket Viewer.
  - Filter
  - Parsing different kind of content based on headers. ( scripts plugin or other ipc method )
- Resend request/response header. (resend a request/response that we already collected.)
- Modify request/response header.

**Comment by mike820324** [comment]
After thinking for a while, I suddenly realize that if we use the req/resp pattern, when the connection_controler crashed, the proxy part will hang, due to waiting for resp.

And as our discussion early this week, the plugins(intercept http content) can held in the proxy part. I believe using the listener pattern may be the correct way to do this.

**Comment by mike820324** [comment]
By the way, if we are using the listener pattern, it seems like we may also need to rename the connection_controller.py into a much proper name.

After applying listener pattern, it will not control the connection, it just receive the data from the proxy and send to other viewing component. ;)

**Comment by mike820324** [comment]
PR #22 fix this issue.
