### ISSUE TITLE
Implement Replay with HTTP2

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#136]
Need following tasks
- [x] Refactor http2layer to extract protocol relative code into another module
- [x] ReplayLayer would handle destination tls handshaking for replay
- [x] Handle replay event with scheme: h2

**Comment by chhsiao90** [comment]
@mike820324 
I had refactor http2 layer.
I had some question, should I create PR for this refactor?

**Comment by mike820324** [comment]
If there are nothing you want to add (the refactor is complete) and the test is all passed, I don't mind you just added to master. Since currently there are no in-progress branch.

**Comment by chhsiao90** [comment]
Got it!

**Comment by chhsiao90** [comment]
Reference #110
