### ISSUE TITLE
[Config]: Refine command line interface and config options

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#137]
The command line interface should be refined to the following format.
## Command line Interface changed:
- remove the following subcommand:
  - proxy
  - console-viewer
  - tui-viewer
- change subcommand into a new command line entry point.
  - microproxy -> start the proxy server and other configuration stuff.
  - mpdump -> original console-viewer subcommand.
  - mptui -> original tui-viewer.
## Command line options and config changed:
- microproxy it self will have both config file and command line options.
- mpdump and mptui will only have command line options since I don't think there will not be too many viewer options that we actually need.
## config.py changed:

Based on the following interface changed, the config.py can be simplify.

**Comment by chhsiao90** [comment]
It took a loooooooooong time to release~~~~
hahaha

**Comment by mike820324** [comment]
I'll deal with this in the weekend. Sadly to say, recently is way too busy.

**Comment by mike820324** [comment]
But I think you can start other features if you want to. The command line interface commits will not influence other component. :)

**Comment by chhsiao90** [comment]
I just want to laugh at you XD.

**Comment by mike820324** [comment]
So sad, I'm going to watch bojack the horse man.
