### ISSUE TITLE
[TUIViewer]: Resize url size based on window size

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#151]
When the terminal size is not longer than url, the whole url will be in the new line. 
It would be better if the url can be changed into the following format when the line is too long.

https://google.com/.....

Also, we can also add a width size limit, when the terminal size is less than that limit, just change the line.

The standard terminal width is 80, which may be a reasonable number.

**Comment by chhsiao90** [comment]
I had do that! With length longer then 100.
Why it not fold on your terminal? Haha!

**Comment by chhsiao90** [comment]
Ok, I will change it to a reasonable limit!
