### ISSUE TITLE
[TUIViewer]: Add keybinding for scroll to the start/end of the page.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#154]
Just a nice to have feature that pressing some key will scroll to the top/bottom of the page.

**Comment by chhsiao90** [comment]
Agreed! I had planned to have this feature at v2.1.2.
But find out that urwid just have home/end for current line navigation, didn't have top/bottom out of box.
So I planned it will provide this feature next version

**Comment by chhsiao90** [comment]
You could key this issue at gviewer, hahaha

**Comment by mike820324** [comment]
Good idea. I'll copy this issue to gviewer.
b.t.w, We don't really need to use home/end, we can use something like vim key binding. (gg, G) for instance.

**Comment by mike820324** [comment]
Tracking https://github.com/chhsiao90/gviewer/issues/23

**Comment by chhsiao90** [comment]
It would be g/G that LIKE mitm did!
What I mean about urwid is they didn't support top/bottom for just use key binding LIKE page down page up.
It need us to control ui manually.
I would take my time to implement it.
But would be soon, haha

**Comment by mike820324** [comment]
Take your time, it's a nice to have feature. Currently the unit test is a much bigger issue. ;D

**Comment by chhsiao90** [comment]
Resolved by #150
