### ISSUE TITLE
[Log]: Proxy will not start if logging.cfg is missing

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#175]
Currently, our logging system is based on the **logging.cfg** config file. If user use setup.py to install microproxy, there will be no logging.cfg and hence failed to start the proxy.

Putting the logging.cfg setting to log.py?

**Comment by chhsiao90** [comment]
Agreed!
We could have load logging.cfg with priority: $current_directory/logging.cfg -> default defined config in log.py

**Comment by mike820324** [comment]
This issue also brings up another design strategy question: The purpose of logging.cfg.

**logging.cfg** is a very powerful logging configuration factor which let you control the behavior of a specific logger, so that we may be able to control the log level, format and handler of a specific logger. However, since it is so powerful and flexible, in order to use logging.cfg, one may also need to have a basic understanding of our code structure.

To talk about logging, I believe there are two aspects to discuss: developer aspect and user aspect.

## User Aspect:

IMHO, I think most of the majority will only want to know: 
- how can I enable/disable log.
- how to config the log level.
- how to write log to a specific files or piped to syslog.

And hence we may be able to add some new command line options:
- log.enable: enable log.
- log.level : specify the log level.
- log.handler: (file | zmq | stdout | syslog)

By using this approach, user may be able to config the logging in a simple manner.

## Developer Aspect:

Now switching back to the developer aspect, If using the above approach, we may not be able to do the following
1. set up a log level for specific logger
2. set up a log handler for specific logger
3. change the formatter

For the first one, even though we can not set the log level for specific logger, there are still alternative approach to reach the same goal. For instance, using grep or view from tui-viewer.

For the second part, I think it is a really rare case to only set handler for certain loggers. If you have some real case, please provide since I haven't use this part at all. ;)

As for the last part, if one want to change the formatter, we may need to step back and think that is the current logging information not enough or too much that cause someone want to change the format of the logger. 

As the above reasons, I think removing the logging.cfg and adding new command line options is a fair trade and reasonable solutions.

How do you think about this?
