### ISSUE TITLE
[Proposal]: Move global instance construction into command_line

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#179]
Global instance is hard to maintain, so I suggest let the initiate actions done by the command_line.py, and put it into context of config attibute.
Like CertStore and Interceptor.
How do you think?

**Comment by mike820324** [comment]
Couldn't agreed more.
The ServerState part will handle this issue either. Currently, I have a WIP branch in my local machine. I'll will continue this working on it until the PR #116 merged.

**Comment by mike820324** [comment]
Reference #147

**Comment by mike820324** [comment]
The **CertStore** and **Interceptor** will be within the server state object which I think is a better place than config.

**Comment by chhsiao90** [comment]
OK, then this issue is duplicate to #147 
Sorry I hadn't noticed that there had bean a issue created for this problem, haha!

**Comment by mike820324** [comment]
No problem.
