### ISSUE TITLE
Add transparent proxy

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#19]
We should be able to accept non socks proxy.

User --- iptables rule or other way ---> proxy.py ----> connection_controller.

If using this way, we can anticipate that the traffic is either http or https data, and should just direct pass to HttpLayer.

**Comment by chhsiao90** [comment]
So is it related to #5 layer design?
To let every layer do things that they need to do without care about other layer do.

And what mode we should provide?
Ex: only forward http/https message without socks
Or any other mode?

**Comment by mike820324** [comment]
> Only forward http/https message without socks

I think this should be enough.

**Comment by mike820324** [comment]
I will start survey this part this weekend.

**Comment by mike820324** [comment]
To get the original destination IP, we can use the `socket.getsockopt` with the following parameters.
- `socket.SOL_IP`
- SO_ORIGINAL_DST=80
- 16

Reference:
https://github.com/apenwarr/sshuttle/blob/9ce2fa00f94c2f2e5c310abeb1a2907ae7e7a7b0/client.py#L86
https://github.com/mitmproxy/mitmproxy/blob/0ab9e60168a2b0ee305ebff47b0532ea7acfecee/mitmproxy/platform/linux.py

**Comment by mike820324** [comment]
After the environment testing is complete, the issue can be closed.

**Comment by mike820324** [comment]
Environment setup as follow,
In linux machine use the following command.

```
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 5580
python main.py proxy --host 0.0.0.0 --proxy_mode transparent
```

Now set up a machine that the gateway is the linux machine.

**Comment by mike820324** [comment]
This issue can be close now.
