### ISSUE TITLE
[TUIViewer]: Mode Indicator

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#190]
Since there are more and more features landed in TUIViewer, I think we can add some mode indicator in the bottom of the tui viewer.
- Main Report: Session View
- Log Report: Log View
- Detail View: Detail View

ex. 
Session [20/30]
Log        [90/300]
Detail

**Comment by mike820324** [comment]
By the way, since there may be some big changes in the proxy itself. I suggest we start work on new feature in the next release.

**Comment by chhsiao90** [comment]
Got it, this make sense!
