### ISSUE TITLE
[TUIViewer]: Adding esc key to escape the search view instead of using q.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#191]
Currently, the behavior of the q key is something like go back to the previous view. And when there is no previous view, we end the tui viewer.

The are two things that I want to propose,
- When the tui-viewer is going to quit, shows a confirm message that will ask the user whether or not he/she want to quit. Just like mitmproxy did.
- Using esc key to escape the search view instead of q.

**Comment by mike820324** [comment]
By the way, since there may be some big changes in the proxy itself. I suggest we start work on new feature in the next release.

**Comment by chhsiao90** [comment]
I think user prompt is better!
Yeah~ 2.0.0 gogo~~ haha

**Comment by mike820324** [comment]
User prompt? you mean pop up a modal window? It would be really nice.

**Comment by chhsiao90** [comment]
The user prompt will show up at the footer, just ask user to enter q to quit!

**Comment by mike820324** [comment]
OK, got it. Just like mitmproxy. XD

**Comment by chhsiao90** [comment]
Reference https://github.com/chhsiao90/gviewer/issues/39
