### ISSUE TITLE
A better design for HTTP Message type

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#2]
Currently, we add serialize and deserialize into the HTTP Message and as a result there are too many common fields in HTTP Message.

Should design a better design for this.

**Comment by chhsiao90** [comment]
I will take care of this! Wait my good news~ yaya

**Comment by mike820324** [comment]
Thank, love you. yeeee~~~
:)

**Comment by mike820324** [comment]
b.t.w, you can still post your idea in here. It would be very helpful.

**Comment by mike820324** [comment]
pull request #17 should fix this issue.
