### ISSUE TITLE
[Performance]: Memory footprint of mptui.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#207]
Currently, we store all the viewer context in memory, and as a result the memory usage will become bigger when we view more sites. 

If we can add a threshold, and when exceed the threshold, the old viewer context will be store in a database or something.

**Comment by chhsiao90** [comment]
It's hard to implement! And I'm not sure that this functionality is useful.
Could you provide a use case that we must or should have this?
I think user could just clear session they don't need.
Thanks!

**Comment by mike820324** [comment]
Actually, I does not come up with a use case yet. XD
It seems pretty reasonable that the user can just clear the unnecessary sessions and keep the session that they interested in.

Thanks to clarify this, I'll close this one.
