### ISSUE TITLE
Plugins Support

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#26]
Should be able to add some plugin script that can manipulate the http traffic.
- intercept http req/resp
- command line options
- dynamic loading

**Comment by mike820324** [comment]
Dynamic loading can accomplish by python importlib module.
The problem is how to trigger proxy to load the plugin script when the proxy is running.

**Comment by mike820324** [comment]
Should at least support the following event.
- **on_start** : will be called when the script is loaded into our system.
- **on_request** : will be called when received the http request.
- **on_response** : will be called when received the http response.
- **on_end** : will be called when the script ended. (system terminated)

**Comment by chhsiao90** [comment]
find solution about dynamic loading from mitmproxy
to load and compile code into dict
and could call script_dict.get(method_name)(args)

loading and compile into dir

``` python
script_dir = os.path.dirname(os.path.abspath(self.args[0]))
self.ns = {'__file__': os.path.abspath(self.args[0])}
sys.path.append(script_dir)
try:
    with open(self.filename) as f:
        code = compile(f.read(), self.filename, 'exec')
        exec (code, self.ns, self.ns)
except Exception as e:
    six.reraise(
        ScriptException,
        ScriptException(str(e)),
        sys.exc_info()[2]
    )
finally:
    sys.path.pop()
return self.run("start", self.args)
```

execute

``` python
if self.ns is None:
    raise ScriptException("Script not loaded.")
f = self.ns.get(name)
if f:
    try:
        return f(self.ctx, *args, **kwargs)
    except Exception as e:
        six.reraise(
            ScriptException,
            ScriptException(str(e)),
            sys.exc_info()[2]
        )
```

**Comment by mike820324** [comment]
Thanks,  I'll take a look in it.

**Comment by mike820324** [comment]
PR #65 fix this issue.
