### ISSUE TITLE
unit test on HttpLayer at proxy.py

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#27]
HttpLayer is one of the core of microProxy.
So write unit test on it is important and we should work on it as soon as possible.
Relative work on it should have:
1. write the unit test code
2. refactor for more testability

**Comment by mike820324** [comment]
Just curious, is it possible to change the **callback style** into the **yielding style** in `HTTPLayer`.
And one more things is that we should seperate the `HTTPLayer` from **proxy.py** into other files or just put it in **http.py**.

**Comment by mike820324** [comment]
tornado iostream has a parameter  called `is_partial`, which may be useful.

**Comment by chhsiao90** [comment]
>  Just curious, is it possible to change the callback style into the yielding style in HTTPLayer.

We could try, but we should consider that in yielding style, could we set up expired time, and how we handle the timeout event in yielding style.

> And one more things is that we should separate the HTTPLayer from proxy.py into other files or just put it in http.py.

Where the class should be defined, and how to name it is very important.
If we put HTTPLayer into http.py, should we also put TLSLayer into http.py?
And HTTPLayer, TLSLayer, DirectServer had same method and all is used to handle the streaming from client(browser), why some named Layer, some named Server? Is their any diifferent?
And is "Layer" a proper name enough to describe their behavior? 

I have no idea about this, just provide my concern and we could discuss about this!

**Comment by mike820324** [comment]
> HTTPLayer, TLSLayer, DirectServer had same method and all is used to handle the streaming from client(browser), why some named Layer, some named Server? Is their any diifferent? And is "Layer" a proper name enough to describe their behavior? 

Good question. Basically, the above three class are doing the same things, at least for now.
The reason I named HTTPLayer and TLSLayer with a layer behind is that if we need to support tls protocol, he TLSLayer may need to  sit under HTTPLayer. This is basically how mitmproxy handle this part.

| SocksHander| --> stream --> | TLSLayer (decrypt) | --> data --> HTTPLayer (parser http)

So, if we are going to refactor the HTTPLayer, we need to consider that in the future we may have to add TLS support and the new design should be able to apply this change without any **big effort**.

I do believe that the above three class should follow the same name or inherit the same base class though.

**Comment by mike820324** [comment]
As for the yielding part, we can handle the connection timeout exception by using try and catch. 
The real question is  the connection timeout period.
Currently, the connection timeout period is using the system default, which is a **very long period**.  I will start survey how to change the connection timeout period when I have freetime.

**Comment by mike820324** [comment]
Find a solution. Using `tornado.gen.with_timeout`.
Example can be as follow,

```
yield tornado.gen.with_timeout(timedelta(seconds=10),  dest_stream.connect(addr_info))
```

http://www.tornadoweb.org/en/stable/gen.html
http://stackoverflow.com/questions/30574012/tornado-future-result-after-timeout

**Comment by chhsiao90** [comment]
got it, I think there is no problem on timeout control! Thanks!
