### ISSUE TITLE
Refine Config and Command line Options

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#35]
Some of the configuration file options and command line options may be the same.
- host
- port

Should find a way that can override the config data.

**Comment by mike820324** [comment]
Would like to add two new config options in Proxy config.
- http.port : additional port for http protocol
- https.port : additional port for https protocol

**Comment by mike820324** [comment]
Moreover, we should be able to override the configuration file settings by command line options. Consider the following scenario.

``` ini
[Proxy]
host=127.0.0.1
port=5580
```

``` sh
python main.py proxy --port=5581
```

**Comment by chhsiao90** [comment]
I think it's a good idea~
