### ISSUE TITLE
Using tornado builtin interface

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#36]
When I first create this project, I'm not that familiar with tornado framework and as a result most of the protocol is implement by ourselves.
Currently, we I looked at the tornado official documentation, I found out several tornado class that serve the same functionality for some of our class.

The following list some of the class that we can survey in the version 0.2.0.
- HTTP Protocol Related
  - `tornado.http1connection.HTTP1Connection`
  - `tornado.http1connection.HTTP1ServerConnection`
  - `tornado.httputil.HTTPHeaders`
  - `tornado.httputil.HTTPServerConnectionDelegate`
  - `tornado.httputil.HTTPMessageDelegate`

The above class may help us get rid of most of our own http implementations. 

As for the TLS Part, reference Issue #4.

**Comment by mike820324** [comment]
Workflow maybe something like the follow.

socks/transparent proxy --src/dest info--> Use `HTTP1ServerConnection` (get request from source stream)/ `HTTP1Connection` (get response from dest stream) to deal with the rest.

By using this approach, we can also drop the http-parser module since tornado has it's own http parsing mechanism which will return `httpclient.HTTPRequest` and `httpclient.HTTPResponse`. 

It seems like tornado has it's own http header parser, `HTTPHeaders`, but I'm not sure about the http body part.

**Comment by chhsiao90** [comment]
I had implement this feature.
But still buggy and cannot pass the unit test.
So I push the code to my repository.
Please help review and advise. Thx.

**Comment by mike820324** [comment]
Actually, you can just commit into my repos branch, no need to worry about the test.
I have added some comments in your code. I will start digging into why the unit test failed.

**Comment by mike820324** [comment]
One more thing, after this everything is done of this issue. We should put **pypy** into `.travis.yml`.
Since we have dropped the dependency of http-parser, pypy should works fine too.

**Comment by chhsiao90** [comment]
for unittest on http layer, I think we could reference tornado unittest template.[Http1Connection](https://github.com/tornadoweb/tornado/blob/master/tornado/test/http1connection_test.py)
That we could test on it by actually create socket connection.

**Comment by mike820324** [comment]
LGTM
