### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#4]
Adding tls support. Maybe reference the approach of mitmproxy.

**Comment by mike820324** [comment]
As previously discussed in Issue #5, it is possible to use '''iostream.start_tls`to change the src stream into the`SSLIOStream```.

The following is a simple snippet that can do the job.

``` python
import ssl                                                                                                                                                                    
try:                                                                                                                                                                          
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)                                                                                                         
    ssl_context.load_cert_chain(certfile="/tmp/cert.crt", keyfile="/tmp/cert.key")                                                                                            
    stream = stream.start_tls(server_side=True,  ssl_options=ssl_context)                                                                                                                                                                                                                                                                                                                                                        
except Exception as e:                                                                                                                                                        
    print e 
```

And using the following command to generate the server certificate and private key.

``` bash
openssl req -new -x509 -days 365 -nodes -out /tmp/cert.crt -keyout /tmp/cert.key
```

**Comment by mike820324** [comment]
One more thing for above snippet, the `ssl.create_default_context` is only available in python 2.7.9 or above. So, if encounter any problem, please check the python verison first.

**Comment by chhsiao90** [comment]
nice work~~

**Comment by mike820324** [comment]
May encounter the following error when serving https://www.apple.com/iphone/

```
2016-05-19 09:35:02,484 - microproxy.layer.http1 - ERROR - [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca
```

**Comment by mike820324** [comment]
And also the following error.

```
2016-05-19 09:36:58,270 - microproxy.layer.tls - ERROR - IOStream is not idle; cannot convert to SSL
Traceback (most recent call last):
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/layer/tls.py", line 22, in process
    src_stream = yield self.context.src_stream.start_tls(server_side=True, ssl_options=src_ssl_context)
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/iostream.py", line 1131, in start_tls
    raise ValueError("IOStream is not idle; cannot convert to SSL")
ValueError: IOStream is not idle; cannot convert to SSL
```

**Comment by mike820324** [comment]
The **IOStream is not idle** problem may be a little bit difficult to solve than I expected.
The problem is caused by the fact that there are already some data in source stream read buffer.
In current tornado design, it is impossible for us to pause the `IOStream.read_to_buffer`, which is what we need in this case.

I may need to survey a while to resolve this issue.

**Comment by chhsiao90** [comment]
It's weird to have this error unless we have some bugs in SocksProxy
According to document from tornado about the IOStream start_tls method:

> This method cannot be used if there are outstanding reads or writes on the stream, or if there is any data in the IOStream’s buffer (data in the operating system’s socket buffer is allowed). This means it must generally be used immediately after reading or writing the last clear-text data. It can also be used immediately after connecting, before any reads or writes.

I had checked our code, and find the last thing we do over the source stream is read_bytes and write,
and we had yield the future to wait for the socket done the action.
I think we should not have any outstanding reads or write over the stream.

Is this error occur frequently?
Or on what situation we will encounter this problem?

**Comment by chhsiao90** [comment]
Because Tornado provide basic ssl context base on server_side or not,
I think we could just doing like this:

``` python
server_ssl_options = dict(certfile=self.context.config["certfile"],
                          keyfile=self.context.config["keyfile"],)
src_stream = yield self.context.src_stream.start_tls(server_side=True,
                                                     ssl_options=server_ssl_options)
dest_stream = yield self.context.dest_stream.start_tls(server_side=False,
                                                       ssl_options=dict(cert_reqs=ssl.CERT_NONE))
```

for moe cleaning style
I had try and it works fine~

**Comment by mike820324** [comment]
I think it's nothing to do with the socks proxy, it's just how tornado iostream works.

Tornado use **epoll** or **kqueue** to implement it's event based system. When a socket receive/write data, iostream will first read/write the data to the `iostream._read/write_buffer`.  As a result, when we reach the `src_stream.start_tls` part, it is highly possible that the browser already sent the client hello to our proxy, and then store inside `iostream._read_buffer`.

I think what the document trying to say is that, if there are data in  `iostream._read_buffer` or `iostream._writer_buffer` , the `start_tls` will failed.

The following is the code in torando iostream. https://github.com/tornadoweb/tornado/blob/master/tornado/iostream.py#L1126

```
 if (self._read_callback or self._read_future or
       self._write_callback or self._write_future or
       self._connect_callback or self._connect_future or
       self._pending_callbacks or self._closed or
       self._read_buffer or self._write_buffer):
    raise ValueError("IOStream is not idle; cannot convert to SSL")
```

**Comment by mike820324** [comment]
By the way, as for the new style, I think it's great. Much more clear than the original one.

**Comment by chhsiao90** [comment]
OK, you are right about the _read_buffer or _write_buffer that the IOStream will buffer the content.
I miss the keyword: must and immediately...

> This means it **must** generally be used **immediately** after reading or writing the last clear-text data.

So the problem is: when we finish the socks handshake and tell the client that I could start read your request, the client will start transmit the request content and the source stream will start buffer from the socket. And error will be raised when tls handshaking is slower than the IOStream read buffer.

I just guess, am I right? yoyo~

But I should say, I hand't seen this error in my macbook.

**Comment by mike820324** [comment]
You are absolutely right, I haven't see this in my macbook too. I believe it's some implementation difference between **kqueue** and **epoll**.

I think I should start merge this PR and add another issue for this. I may need to add some new code, but this PR may killing me if I have to rebase it. XDDD

Do you have any other stuff need to add for this PR??

**Comment by chhsiao90** [comment]
Let's just merge it!
