### ISSUE TITLE
Viewer Enhancement

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#42]
We only have one viewer now. We should add more viewer type and rename the current one into different name.
- log -> basic 
- web
- tui

**Comment by mike820324** [comment]
Reference Sites for color printing.
- https://pypi.python.org/pypi/colored
- https://pypi.python.org/pypi/colorama
- https://pypi.python.org/pypi/termcolor

**Comment by chhsiao90** [comment]
I had refactor the color printing code, please have a look at it!
https://github.com/mike820324/microProxy/commit/ec75bda2a612a702b1d4102c1d8e7e0b8584c363

**Comment by chhsiao90** [comment]
The code you commit looks good to me and thx for your refactor
https://github.com/mike820324/microProxy/commit/17f0072d29db48389e19f80bac5cee72bcac3d78
https://github.com/mike820324/microProxy/commit/96e1a4f0c83a738a336d47cc006ba32d851281eb

BUT.... please don't give up with you CONSOLE mode viewer. HAHAHAHA

**Comment by mike820324** [comment]
The tui is way too fancy, I just can't help it but continue working on it. :D
