### ISSUE TITLE
Add Candidate for config file.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#43]
We only read the config file either from command line options or current folder.

I think we can add more candidate for config files.
1. command line option
2. current folder
3. home folder of current user
4. /usr/local/etc/application.cfg
5. /etc/application.cfg

**Comment by chhsiao90** [comment]
I suggest we should just simplified the feature with

> 1.command line option
> 2.current folder

Following config file path could just use the option 1 to define the config path

> 3.home folder of current user
> 4./usr/local/etc/application.cfg
> 5./etc/application.cfg

**Comment by mike820324** [comment]
Fair enough. I'll close this issue. ;)
