### ISSUE TITLE
Layer Design

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#5]
If we need to add #4 tls support, we may need a layer design. The same as mitmproxy did.

**Comment by mike820324** [comment]
What I came up with so far is that we separate the stream read/write logic out of the **layer** related classes. 

When StreamManager yield some data, it will pass the receive data to LayerManager. The LayerManager will then pass the data to different layers. 
Each layer is responsible for it's own parsing task. ex. TLS is responsible for decrypt the message and pass to a higher layer. and HTTP is responsible for parsing the HTTP headers and body.

**Comment by mike820324** [comment]
I should define the expected behaviors of  Layer before think about how to implement them.
As I can tell, each layer may have the following two behaviors:
- Negotiation: Protocol specific negotiation. TLS client hello, socks, http.
- Changing Stream Data: Will have to change the receive content before sending to next layer. (TLS need to decrypt received data before sending to next layer.)

The negotiation behavior is much easier to implement since after the negotiation is done, we can safely pass control to the next layer. Take the http2 as an example.
1. client send socks request (Socks Negotiation Start)
2. proxy response socks request ( Socks Negotiation Complete, transfer control to http layer)
3. client send http upgrade ( HTTP Negotiation Start )
4. proxy forward http upgrade to server. 
5. server reply 200 OK. 
6. proxy forward 200 OK to client. (HTTP Negotiation Complete, transfer control to http2 layer) 
7. http2 layer take control.

However, some layer have to change the stream they receive before passing to  the next layer. Take https as an example.
1. client send socks request (Socks Negotiation Start)
2. proxy response socks request ( Socks Negotiation Complete, transfer control to tls layer)
3. client send TLS Handshake (TLS Negotiation Start)
4. proxy Handshake with both side and hence get the session key. (TLS Negotiation Complete)
5. TLS Decode new receive data and pass the data to HTTP Layer. ( This part is difficult to implement)

What I can think off so far to solve this kind of scenario without breaking the yield pattern is that, after TLS Handshake is complete,  we wrap the iostream instance. So that whenever HTTP layer called `iostream.read()/write()` it will go through the decryption process.

**Comment by chhsiao90** [comment]
for TLS part,
after TLS handshake, we wrap src_stream and dest_stream with tornado SSLIOStream and pass it to HTTPLayer.
Should this solution work?

**Comment by mike820324** [comment]
Since we can control the connection of dest stream, I believe that SSLIOStream is perfectly suitable for dest stream. 
As for the src stream, I have to test it before I can answer.

One more thing, I want to add two new fields in configuration file. 
- http.port
- https.port

which the user can add additional http/https port. In this way, we can just decide which handler in ProxyHandler, and do not need the **is_tls_protocol** magic.  Hence simplify the layer design.

**Comment by mike820324** [comment]
I have done a quick test and the `iostream.start_tls` should work as it should be.
However, I haven't test the SSLIOStream yet.
