### ISSUE TITLE
Refine Interceptor

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#59]
Currently, interceptor is not interceptor.
It didn't change request/response content.
It just log or publish content to viewer.

I think we should:
1. rename interceptor to publisher
2. remove request and response method
3. rename record to publish

**Comment by mike820324** [comment]
This issue is related to issue #26. Will be fixed in the PR that is related to #26.

**Comment by mike820324** [comment]
PR #65 fix this issue.
