### ISSUE TITLE
[TlsLayer]: Better TLS handling

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#61]
Current tls layer implementation has use many incorrect settings when connecting to destination side.
- version
- alpn/npn protocol
- sni

the above three resource can be get by the source stream.
- `src_stream.socket.version()`
- `src_stream.socket.selected_alpn_protocol()`
- `SSLContext.set_servername_callback()`

Reference:
- https://docs.python.org/2/library/ssl.html#ssl.SSLSocket.version
- https://docs.python.org/2/library/ssl.html#ssl.SSLContext.set_servername_callback
- https://docs.python.org/2/library/ssl.html#ssl.SSLContext.set_alpn_protocols

**Comment by mike820324** [comment]
A simple workflow maybe first register a callback in `src_stream` by `SSLContext.set_servername_callback()`.

Within the callback function, we can get the following resources
- sni
- alpn

By using these two resource, we can `start_tls` for `dest_stream` and get the alpn value from the server. 
Finally we use the alpn value that get from the server and return to the client.

**Comment by chhsiao90** [comment]
Yeah~ I was thinking about this too.
We should finish tls handshaking on client before we done the tls handshaking on server.
So that we could help client and server to exchange the protocol information!

**Comment by mike820324** [comment]
The sni part can be solved in a simple manner. 

However the alpn part may be a little bit trickier than I expected.
In order to let the alpn properly, the flow should be like the following:

client ---------- proxy ---------- server
1. client send client hello with it's alpn
2. proxy receive **client alpn** and start tls negociation with server using the **client alpn**.
3. tls between proxy and server is done. 
4. proxy get **server alpn** from the step 3 and response **server alpn** to the clinet.

The only way to get the client alpn is by register a callback using `SSLContext.set_servername_callback()`.
However, within the callback, we can not using the tornado yielding or the ssl module will throw error to us.

In order to fix this problem, we may need to modify the `dest_stream` code to do_handshake by ourselves instead of calling `SSLIOStream.start_tls`.

**Comment by mike820324** [comment]
So the alpn support is finally finished. But the code is a little bit messed up. I will take some time to clean it up. 

b.t.w, I have used pyenv to install python 2.7.11 and get the alpn support. Maybe I should update documentation to mention about this.

**Comment by mike820324** [comment]
In order to use pyopenssl, we may need to change the inherit the following tornado class and override some of the methods.
1. Inherit `iostream`: override the `self.start_tls`, so that we can apply pyopenssl context.
2. Inherit `ssliostream`: override the `self._handle_ssl_handshake` and `self._verify_cert`, so that we can apply pyopenssl exceptions.
3. Inherit `tornado.tcpserver.TCPserver`: override `self._handle_connection`, so that we can use our own `iostream`.

Inherit the TCPserver are really been done in proxy.py, we only need to override `self._handle_connection`.
The following is a snippets.

```
def _handle_connection(self, connection, address):
    try:
        stream = iostream.IOStream(connection,
                                                                          io_loop=self.io_loop,
                                                                          max_buffer_size=self.max_buffer_size,
                                                                          read_chunk_size=self.read_chunk_size)
       future = self.handle_stream(stream, address)
       if future is not None:
           self.io_loop.add_future(future, lambda f: f.result())
    except Exception as e:
        logger.exception(e)
```

If one day, we have add a new IOStream we can apply in here, so that the `start_tls` can act properly.

**Comment by mike820324** [comment]
The latest commit for sni-alpn branch has complete most of the features, the only thing we need is to update the test.

**Comment by mike820324** [comment]
PR #63 fix this issue.
