### ISSUE TITLE
[TlsLayer]: Generate client certificate on the fly

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#68]
Currently, we use the following command to generate a certificate for all website.

```
openssl req -new -x509 -days 365 -nodes -out /tmp/cert.crt -keyout /tmp/cert.key
```

Since the CN field of the certificate must much the domain name of a website, the firefox will complain about this whenever we use the certificate.

A better approach is to use the original certificate as the root CA, and whenever a new connection come in, we will sign the certificate on the fly and return to the user. 

In this way, if we have already import the old certificate as root ca, the firefox will not complain about the certificate.

**Comment by mike820324** [comment]
Reference Code:
https://github.com/mitmproxy/mitmproxy/blob/master/netlib/certutils.py#L82

Reference Site:
https://pyopenssl.readthedocs.io/en/stable/api/crypto.html
https://blog.didierstevens.com/2008/12/30/howto-make-your-own-cert-with-openssl/

**Comment by mike820324** [comment]
May also need to change the command line options,
-  `--cert-file` -> `--ca-cert-file`

**Comment by mike820324** [comment]
@chhsiao90 should I add a new method in `tlslayer` or add a utility function in util.py?

**Comment by chhsiao90** [comment]
Either the approach is fine to me.
And it's cool to generate ca on the fly.
Awesome! Haha
