### ISSUE TITLE
[Perf]: Use concurrent.futures in some blocking code.

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#74]
Some of the code will block the whole tornado ioloop, we may consider using different executor of concurrent.futures to improve performance.
- destination dns resolve
- destination connect
- plugins

**Comment by chhsiao90** [comment]
I'm not sure what do you mean runing future in different executor will improve performance?
Do you have reference?

Some document I had read from tornado but didn't mention about this:
[coroutine-patterns](http://www.tornadoweb.org/en/stable/guide/coroutines.html#coroutine-patterns)
[Threading and concurrency](https://github.com/tornadoweb/tornado/wiki/Threading-and-concurrency)

**Comment by mike820324** [comment]
Think of the destination connect case. We will have a timeout to wait for the connection to complete. This kind of waiting process will definitely block the whole tornado ioloop since they are in the same thread. And hence, will not serve other connection.

Using ThreadPoolExecutor for this kind of blocking code, we can put the code to another thread and yield the execution context back to the ioloop so that it can still serve other request.

**Comment by mike820324** [comment]
The Item 3 of [Threading and concurrency](https://github.com/tornadoweb/tornado/wiki/Threading-and-concurrency) has mentioned the ThreadPoolExecutor which is within concurrent.futures.

And Tornado coroutine can also handle the Future class of  concurrent.future module.

A quick example can be found in this page.
https://mike.depalatis.net/running-possibly-blocking-code-like-a-tornado-coroutine.html

**Comment by chhsiao90** [comment]
I know  why I'm confused on it.
Because I had just found that we connect to destination with blocked socket that was not controlled by tornado iolooop...

``` python
def create_dest_stream(self, dest_addr_info):                         
    dest_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
    dest_socket.setblocking(True)                                     
    # FIXME: using concurrent.futures ThreadExecutor?                 
    dest_socket.settimeout(3)                                         
    dest_socket.connect(dest_addr_info)                               
    dest_socket.settimeout(None)                                      
    return dest_socket                                                
```

Is that true we could not use IOStream from tornado here because of TLS?

**Comment by mike820324** [comment]
Good point. I'm not quite sure either. 

Using this kind of approach is kind of dangerous and unclear to other people. Since we have to set the destination stream to non blocking mode after the tls layer and this is why there is also a NonTLS layer right there, to overcome this problem.

We should discuss this part to see whether there is a better approach.

**Comment by chhsiao90** [comment]
I had some modification:
- MicroProxyIOStream with detach function (idea is from start_tls, that start_tls discard origin IOStream and create new IOStream)
- After SocksLayer or TransparentLayer that the type of src_stream and dest_stream are always IOStream or class extend from it, keep the consistency. (Original, dest_stream will sometimes be Socket)
- No need to call pause/resume over source stream
- detach dest_stream when it need
